name: 'Bot Notifications'
description: 'A simple bot notification by github actions'
author: 'hb0730 <1278032416@qq.com>'
inputs:
  webhook:
    required: true
    description: 'The webhook url'
  secret:
    required: false
    description: 'The secret'
  bot:
    required: true
    description: 'The bot type,default: feishu'
    default: 'feishu'
  msg_type:
    required: true
    description: 'The msg type,default: text'
    default: 'text'
  simplified:
    required: false
    description: 'The content is simplified'
    default: 'true'
  content:
    required: false
    description: 'The content'
    default: 'Hello World'
  job_status:
    required: true
    description: 'Actions build status (e.g. success, failure, cancelled)'
  on_notification:
    required: true
    description: 'when to notify, default: always, "always", "success", "failure", "cancelled"'
    default: 'always'
  on_failure_at_all:
    required: false
    description: 'Only on failure at all, default: false,template string ${@all} will be replaced'
    default: 'true'
outputs:
  response:
    description: 'The bot response'
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  color: 'purple'
  icon: 'bell'
